### ISSUE TITLE
"Blocked loading mixed active content" error in secure notebooks

### ISSUE THREAD

**Issue by mnowotka** [mpld3/mpld3#115]
Hi,

Imagine I'm running my own ipython notebook server. As a reasonable person I probably set up password authentication as well as secure connection via https. This second thing will cause problems with mpld3. Why? By default mpld3 tries to fetch D3 (and require.js) from `http://d3js.org/d3.v3.min.js` and if server is running on https this will cause "Blocked loading mixed active content". So why not change default urls to https like `https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.4/d3.min.js` or just add simple `use_https` to `enable_notebook()` function?

**Comment by iamonuwa** [comment]
Use //url
