### ISSUE TITLE
Display multiple mpld3 exports on a single HTML page

### ISSUE THREAD

**Issue by philsheard** [mpld3/mpld3#128]
I've been trying to work out how to export multiple individual figures to display them in a template using Flask. I think the solution is somewhere between the `.fig_to_html` and `.fig_to_dict` methods but I'm not JS-savvy enough to work it through.

There's a fuller description on this stackexchange question:
http://stackoverflow.com/questions/22981359/display-multiple-mpld3-exports-on-a-single-html-page

I'd be happy to submit an pull request to the docs if someone can explain what's needed.

**Comment by drvinceknight** [comment]
@jakevdp I apologise for my ignorance and/or inability to find how to do this but how would I embed a json output of mpld3, using:

```
mpld3.save_json(fig, 'random_choice.json')
```

into an html slide deck? For clarity, I would rather not clip the json in to the html directly (as I want to be able to rerun my python script to obtain the plots). I'm guessing I'm just missing some basic json/html knowledge...

**Comment by jakevdp** [comment]
Yes, you'd have to write a one-liner to load the JSON into javascript, and then call ``mpld3.draw_figure(json)``

A google search turned-up this: http://stackoverflow.com/questions/7346563/loading-local-json-file

**Comment by drvinceknight** [comment]
I've been trying that (I really don't know what I'm doing here). So would
this be the line I need before your suggestion?

```
var json = $.getJSON("test.json");
```

Are there any libraries or js I need to put somewhere? (currently have
terrible WiFi so google-ing isn't that easy and I think that with a lot of
this explanations expect a certain entry level that I am not at :().

Thank you very much for your response! :)

**Comment by aflaxman** [comment]
I would use `d3.json` to load the json, since you'll need that anyway for `mpld3`.  Here is the javascript to do it:
```
      d3.json("test.json", function(error, json) {
        if (error) return console.warn(error);
        mpld3.draw_figure("mplplot", json);
      });
```

And here is [a notebook that puts it together](https://gist.github.com/aflaxman/0966ebf06e23e13db1a1), which you will have to download and open with your own IPython because nbviewer is too paranoid to display it.

**Comment by drvinceknight** [comment]
Thanks Abraham,

I'll try that out!

Vince

**Comment by aarumuga** [comment]
I am trying to display multiple htmltooltip plugin plots in a page. The plots shows up. But the HTMLtooltip plugin doesnt work.
