### ISSUE TITLE
How to make larger plots?

### ISSUE THREAD

**Issue by wfbradley** [mpld3/mpld3#175]
Forgive me if this the wrong forum to ask a question like this; I wasn't sure where else to ask it.  If I plot a curve, the resulting image seems to have a standard size on my browser (it's about 2x3 inches).  I'd like to render a larger image.  How do I do that?  I couldn't find an example of that among the examples or documentation, but maybe I missed it.

Incidentally, if I zoom in my browser (cntl-+), the image _does_ get larger, but unfortunately so does the text.

  Thank you,
  Bill

**Comment by eduardorochasoares** [comment]
How to set position of the graphic on browser?

**Comment by sjlukacs** [comment]
i've set figsize to (2,1.5), (4,3), (8,6), (16,12), (32,24) and none changed the size on the web page.  any other suggestions?

**Comment by ckerr-IDM** [comment]
@sjlukacs I'm having trouble reproducing the problem for me,  -- could you please share the code you're using? I just tried this example, and it works for me to change `figsize` from e.g. `(10,10)` to `(10,5)`:

```
import pylab as pl
import mpld3

figsize = (10,5)
fig = pl.figure(figsize=figsize)
x = pl.rand(10)
pl.plot(x)
mpld3.show()
```

**Comment by sjlukacs** [comment]
os.environ['MPLCONFIGDIR'] = tempfile.mkdtemp()
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as mat_plt, mpld3

def plot(array):
    mat_plt.style.use('dark_background')
    mat_plt.figure(figsize=(2, 1.5))
    fig, ax = mat_plt.subplots()
    ax.plot(array[0], array[1], 'ow', linewidth=1.5, markersize=6.0)
    make_html = mpld3.fig_to_html(fig)
    mat_plt.close('all')
    return XML(make_html) #XML is part of web2py, it escapes the html

**Comment by ckerr-IDM** [comment]
Hi @sjlukacs , sorry for the slow reply. The problem is with:
```
mat_plt.figure(figsize=(2, 1.5))
fig, ax = mat_plt.subplots()
```
The first line creates a figure of the correct size which isn't used, while the second line creates a figure of default size. You can replace both these lines with:
```
fig, ax = mat_plt.subplots(figsize=(2, 1.5))
```

In general, it's usually a good idea to debug the Matplotlib figure first before trying to debug the mpld3 figure (of course for this you'll need to comment out `matplotlib.use("Agg")` as well).
