### ISSUE TITLE
   raise TypeError(repr(o) + " is not JSON serializable") TypeError: array([   0.,  800.]) is not JSON serializable

### ISSUE THREAD

**Issue by Vikramank** [mpld3/mpld3#223]
Hi, 
I'm trying to render a 3D plot from Matplotlib to the browser. I got the above error. 
Any suggestions?
part of my code:
X = np.arange(1,801)
Y = np.arange(1,161)
X, Y = np.meshgrid(X, Y)

fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, np.transpose(a), rstride=1, cstride=1, cmap='hot', linewidth=0, antialiased=False)
ax.set_zlim(-1.01, 1.01)

fig.colorbar(surf, shrink=0.5, aspect=5)
plt.show() 
mpld3.show()

**Comment by cqcn1991** [comment]
@Vikramank Hi, I'm having the same problem. Is there any good way to interact 3d plot (e.g. surface) now?

**Comment by Vikramank** [comment]
@cqcn1991 Hi, yes indeed. But you need to use jQueery/JS library called d3js. It's an awesome library and relatively easy to learn and use. Check this example for 3D plot.
http://bl.ocks.org/supereggbert/aff58196188816576af0

Best, 
K.Vikraman

**Comment by yesicamilagros** [comment]
how can I make it ? about the exercise
