### ISSUE TITLE
error: package directory 'mpld3/mplexporter' does not exist

### ISSUE THREAD

**Issue by honglei** [mpld3/mpld3#249]
F:\0926\mpld3-master>python setup.py build
running build
running build_py
creating build
creating build\lib
creating build\lib\mpld3
copying mpld3\mpld3renderer.py -> build\lib\mpld3
copying mpld3\plugins.py -> build\lib\mpld3
copying mpld3\urls.py -> build\lib\mpld3
copying mpld3\utils.py -> build\lib\mpld3
copying mpld3_display.py -> build\lib\mpld3
copying mpld3_server.py -> build\lib\mpld3
copying mpld3__about__.py -> build\lib\mpld3
copying mpld3__init__.py -> build\lib\mpld3
error: package directory 'mpld3/mplexporter' does not exist

F:\0926\mpld3-master>python
Python 2.7.7 |Anaconda 2.0.1 (64-bit)| (default, Jun 11 2014, 10:40:02) [MSC v.1
500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org

**Comment by JamesMTSloan** [comment]
My installation is failing at the same point. I have downloaded the zip from github and ran python setup.py install but got this error. Having found this report I tried installing mplexporter which apparently installed successfully but further attempts installing mpld3 still failed. I also tried python setup.py submodule which did not work. I am behind a corporate firewall so I can't use pip or any other package manager.

writing mpld3.egg-info\PKG-INFO
error: package directory 'mpld3/mplexporter' does not exist

is the error I get in command prompt on windows running python 3.4 anaconda distribution.

**Comment by jakevdp** [comment]
This is the problem here: I just learned yesterday that git submodules don't make it into the zip download from github. The issue is actually deep within git itself. I'd suggest either installing from pypi, or downloading the source via github. The zip file from github will not work, unfortunately.

**Comment by JamesMTSloan** [comment]
OK cloning from github has worked fine on linux at home. I had tried pip at first but the example plots failed because I am using python 3.4, as mentioned in another post on here. I should now be able to take the cloned repo to work and install with that. Cheers.

**Comment by jakevdp** [comment]
Yeah, we need a new release so that mpld3 will work with 3.4

I've been absolutely swamped, so I haven't had the ~half day that it takes to release mpld3 (JS release + python release + lack of JS unit tests makes things very time-consuming).

**Comment by avipersin** [comment]
Had the same issue using windows.  First used pip to install and realized it wouldn't work with python 3.4.  

Then, downloaded the zip and ran "python setup.py submodule; python setup.py install" and got "error: package directory 'mpld3/mplexporter' does not exist".  

Finally googled the error and ended up here.  Cloned the repo, rebuilt, and everything worked.

**Comment by jakevdp** [comment]
Master works with 3.4. Any documentation updates will come with a new release, so that will take care of 3.4 compatibility.

I continue to be absoutely swamped – any volunteers for doing a release?

**Comment by danielballan** [comment]
I can give this half a day this week, but I've only been keeping half an eye on the issues as they go by. Are there any blockers left?

**Comment by jakevdp** [comment]
I think at this point, we just want to get a release out. By the nature of this project, there will always be bugs – we're never going to hit 100% coverage of all versions of matplotlib (at least, not until the mpl serialization framework is in place – then we can think about it)

**Comment by jakevdp** [comment]
I think the main thing is to make sure unit tests pass, and also make sure that all the examples plots work. That's what stopped me from releasing last time I took a shot at it.
