### ISSUE TITLE
Text "None" at the bottom left of the plot when using legend

### ISSUE THREAD

**Issue by ocefpaf** [mpld3/mpld3#275]
I am not sure if this is an issue with mpld3 or mplexporter.  When I create plots using matplotlib's legend I see a text "None" added to the lower left of the plot.

![mpld3_legend](https://cloud.githubusercontent.com/assets/950575/5691940/8c447b4a-98bd-11e4-80dd-8577dc970d85.png)

``` python
import mpld3
import numpy as np
import matplotlib.pyplot as plt


fig, ax = plt.subplots()

x = np.linspace(0, 10, 100)
ax.plot(x, np.sin(x), label='sin', lw=3, alpha=0.5)
ax.plot(x, np.cos(x), label='cos', lw=3, alpha=0.5)
ax.plot(x[::5], 0.5 * np.sin(x[::5] + 2), 'ob', label='dots')

ax.legend(fancybox=True)
ax.set_title("Legend test", size=20)

html = mpld3.fig_to_html(fig)

mpld3.fig_to_dict(fig)['axes'][0]['texts'][1]['text']
Out[7]: 'None'
```

**Comment by jakevdp** [comment]
Yes, I see that as well. I'm not sure where that's coming from – we'd have to dig through to figure it out.

**Comment by ocefpaf** [comment]
For the record, in case find this issue looking for a solution, this is a ~~workaround~~ horrible hack, to eliminate the "None" when saving HTML:

```python
def save_html(fig, fname):
    html = mpld3.fig_to_html(fig)
    html = html.replace('"text": "None"', '"text": ""')
    with open(fname, 'w') as f:
        f.writelines(html)
```

**Comment by jakevdp** [comment]
Nice :smile:

A bit more info: I believe the "None" is the legend title, which matplotlib keeps around even if you're not using it. Somehow the renderers know to hide the title if it's not set, though I'm not sure how that happens.

**Comment by ocefpaf** [comment]
Good to know!

```python
l.set_title("")
```

is a better work-around.

**Comment by ivanchaer** [comment]
I was having the same problem, and managed to have the 'None' disappear by specifying title='', as in:
ax.legend(loc='upper left', fancybox=True, title='')

**Comment by kubark42** [comment]
@ivanchaer's workaround worked for me as well.

**Comment by etgalloway** [comment]
In matplotlib, the value of the legend title is the "None" string (in agreement with the comment by @jakedvp above):

```python
>>> print(ax.legend_._legend_title_box._text)
Text(0,0,'None')
```

The legend title is not displayed in matplotlib because it's not visible:

```python
>>> print(ax.legend_._legend_title_box._visible)
False
```

As fixes, the alternatives include (1) modifying `matplotlib.text.Text.set_text` so that it converts
None arguments to the empty string (instead of "None") or (2) adding more support for visibilities to 
`mplexporter` and `mpld3`.

**Comment by tacaswell** [comment]
2 is clearly the better option here :wink:

**Comment by ocefpaf** [comment]
Closing this. Not sure if the issue is fixed but it is easy to workaround it.
