### ISSUE TITLE
dots connecting when they should not

### ISSUE THREAD

**Issue by aflaxman** [mpld3/mpld3#367]
In the code in the current master branch, dots are connecting up when they should not be.  Here is an example from the legend test plot:

![image](https://cloud.githubusercontent.com/assets/51236/15694327/7f7c733a-2751-11e6-8628-916739a0f5fd.png)

**Comment by genomematt** [comment]
I don't see this @aflaxman 
I did a cleanish install, new fork, clone, follow CONTRIBUTING.md, install with `pip3 install --editable .`

Versions:
matplotlib (1.5.1) nose (1.3.7) numpy (1.11.1) pandas (0.18.1) pip (8.1.2) pytz (2016.6.1) pyzmq (15.2.0) qtconsole (4.2.1) scikit-learn (0.17.1) scipy (0.18.0) setuptools (19.4)

![screen shot 2016-08-02 at 11 40 48 am](https://cloud.githubusercontent.com/assets/2321218/17314235/0e45430a-58a6-11e6-8fac-5b6b0f870f24.png)

**Comment by genomematt** [comment]
Ok, did a Python2.7 install and see it there.

**Comment by aflaxman** [comment]
time to end python2 support?  just kidding.  i think that this project is always going to be a mess due to its bolt-on nature.  so a work-around fix is fine while we wait for an upstream fix.  If you have time, please consider a pull request.

**Comment by genomematt** [comment]
That work around is not compatible with python 3.0 and 3.1 and it is a string I set.  It may be possible to protect it with a lazy `or` but not sure if that works. If I can work out how to ensure that is str not u that would be a much better fix.  Having mixed string types in a dictionary seems too much like a bug waiting to happen again, as from memory there are some versions of python2 that will segfault if you do `'default' is u'default'`

**Comment by genomematt** [comment]
Ok I have a fix that will work and won't kill python 3.0/3.1.   The unicode is emanating from matplotlib get_drawstyle so we need to handle it.  Fix is entirely in mplexporter so I will create a pull request there.

**Comment by genomematt** [comment]
@aflaxman you will need to update the subproject after you have merged my mplexporter pull request

**Comment by etgalloway** [comment]
@genomematt, in `mplexporter/exporter.py`, you should compare the drawstyle value using `==` not `is`:
```bash
diff --git b/mplexporter/exporter.py a/mplexporter/exporter.py
index f1b9330..083ceb6 100644
--- b/mplexporter/exporter.py
+++ a/mplexporter/exporter.py
@@ -187 +187 @@ class Exporter(object):
-                and linestyle['drawstyle'] is 'default'):
+                and linestyle['drawstyle'] == 'default'):
```

I believe that this (by itself) is the fix for this particular issue.

**Comment by genomematt** [comment]
u'default' == 'default' is only true when encoding is UTF-8
If we could be sure it would always be UTF-8 that would be enough.  Do any platforms default to UTF-16?

**Comment by genomematt** [comment]
The only cases where this doesn't work based on my research and trials throw an informative warning so I have updated the pull request.  Thanks @etgalloway !

**Comment by aflaxman** [comment]
I have attempted to update the submodule.  Lets see if it works.
