### ISSUE TITLE
Installing matplotlib on production needs numpy dependency installed at first in AWS EB server

### ISSUE THREAD

**Issue by guganselvaraj** [mpld3/mpld3#373]
The package is working apreciably awesome ! but when deploying to the production server the installation of matplotlib needs numpy to be installed prior ! i read few documentations but there are no proper clarifications made ! Help me configuring the server with matplotlib and numpy for mpld3 to work on production ! 
My production server is AWS Elasticbeanstalk

**Comment by jakevdp** [comment]
NumPy is a requirement for matplotlib, so you'll need to install it to use matplotlib. You might check with the matplotlib mailing list if that is a problem for you. Thanks!
