### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by erickmiller** [mpld3/mpld3#377]
I followed the **setup.py** steps for installation and think everything is installed properly, but when I try to run **create_examples.py** it does this:

**Traceback (most recent call last):**
  File "create_example.py", line 10, in <module>
    **page = urllib2.urlopen('http://d3js.org/d3.v3.min.js')**
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
**urllib2.HTTPError: HTTP Error 403: Forbidden**

Also, in a shell, running   **pip show mpld3** Returns this:
_Name: mpld3
Version: 0.2
Location: /usr/local/lib/python2.7/dist-packages
Requires:_ 

But running **version.py**  from the git repo returns this:
_0.3git_

This project looks awesome but so far haven't got it to work and am a bit confused why this error is happening. 

Any idea what could be causing this?   I'm able to read and access http://d3js.org/d3.v3.min.js via web browser with no problems from my computer (Ubuntu 15.10 python2.7) . 

Thanks

**Comment by erickmiller** [comment]
After a bit more poking around and testing it appears this error is only with create_examples.py and does not cause the rest of the library problems; I was able to locally run the code from here, launch a web server and visualize the awesomeness: 
http://mpld3.github.io/examples/custom_plugin.html

Next will look into drawing my own from matplotlib graphs I'm making.  Very cool.

**Comment by erickmiller** [comment]
It's only the create_examples.py script that failed which is a non critical error and I may have been using it wrong anyways, so I'm going to close this issue.  This is an awesome library by the way.

**Comment by etgalloway** [comment]
Thanks for reporting this.

`create_example.py` does not need to download `d3.js` -- it's installed with `mpld3`.
