### ISSUE TITLE
v0.3 Release

### ISSUE THREAD

**Issue by etgalloway** [mpld3/mpld3#398]
I think it's finally time to release v0.3.

Existing related issues: #278, #303, #311, #379.

The automated JavaScript and Python tests have been fixed (with one exception). The JS tests were fixed in #376 and #384.  Python tests (for `mplexporter`) were fixed in mpld3/mplexporter#48, and mpld3/mplexporter#50.

The one exception is the `mplexporter` image test. It is actually easy to fix, if 'fix' is the right word (see mpld3/mplexporter#49). It is not really clear to me that it is a well formulated test. In any case, it was agreed in mpld3/mplexporter#29 that it would be skipped.

There are a few known issues with the visual tests. For completeness, here is a list:
- Infinity/NaN marker filtering is not quite correct, #385. This affects
  `test_inf.py`.
- Line markers are missing from scatter plot legends, #264, #290.
  This affects `test_legend_scatter.py`.
- Tick label rotation is not supported, #369.  This affects `test_date.py`.
- Tooltips do not work if box-zoom is activated, #165.
  Affects `test_line_HTMLtooltips.py`, `test_line_tooltips.py`,
  `test_tooltips_basic.py`, `test_tooltips_labels.py`,
  `html_tooltips.py`, `scatter_tooltip.py`
- In the [random_walk.py](http://mpld3.github.io/examples/random_walk.html) example, box-zoom disables line highlighting.

I don't believe that any of these are quick and easy fixes.

I am not aware of any open issues that are regressions relative to v0.2.

**Comment by etgalloway** [comment]
I'm working my way through RELEASING.md ... currently on step 11, PyPI upload.

This is a step I can't do because I'm not listed as a PyPI maintainer.

cc: @aflaxman, @jakevdp.

**Comment by jakevdp** [comment]
Hi @etgalloway – do you have a PyPI account? I'd be happy to add you as an owner

**Comment by etgalloway** [comment]
I do, my username is Eric.Galloway.

**Comment by aflaxman** [comment]
I don't have one, maybe I should create and be added, also. (Although I am _very_ happy to have @etgalloway doing this work!!!)

**Comment by aflaxman** [comment]
I have one now.  username `aflaxman`.

**Comment by jakevdp** [comment]
OK, you're both owners on PyPI. Thanks for tackling this!

**Comment by etgalloway** [comment]
Thanks @jakevdp!

**Comment by etgalloway** [comment]
v0.3 is now available on GitHub as a release.  This is the result of some automagic -- pushing a version tag  to Github creates a release.

Not sure why GitHub converts tags into releases.

Unfortunately, I noticed after uploading v0.3 to [testpypi](https://testpypi.python.org/pypi/mpld3) that parts of the README  and the python version classifiers in setup.py  are out of date.

I guess I should have uploaded to testpypi before pushing the tag to GitHub.

Should I go ahead and upload mpld3 as is to pypi? Trying to avoid two different versions of the release.

pypi does allow for [post releases](https://www.python.org/dev/peps/pep-0440/#post-releases) to fix errors in release notes, etc.

**Comment by bryevdv** [comment]
It's also possible to delete the tag and the release tarball from github and start over.

**Comment by ocefpaf** [comment]
@etgalloway I the `mplexporter` directory is empty on the GitHub release (it is a submodule). Also, the imports inside mpld3 changed to use relative imports, rendering external installation of `mplexporter` useless as a workaround.

I tried to package it here: https://github.com/conda-forge/mpld3-feedstock/pull/5 BTW.

**Comment by ocefpaf** [comment]
> It's also possible to delete the tag and the release tarball from github and start over.

Possible, but will drive packagers like me mad :imp:

The `hash` changes, the build breaks, and all that fun we love to hate :stuck_out_tongue_winking_eye:

**Comment by bryevdv** [comment]
There are fewer package managers than users. You always have to do what's best for users, regardless.

**Comment by ocefpaf** [comment]
> There are fewer package managers than users. You always have to do what's best for users, regardless.

I do not dispute that. But you can make both happy and issue a `post` release on Github too and keep it in sync with PyPI. Good practices never hurt anyone :wink: 

PS: See how `fiona` does it as an example: https://github.com/Toblerity/Fiona/releases

**Comment by bryevdv** [comment]
> I do not dispute that. But you can make both happy and issue a post release on Github too and keep it in sync with PyPI. 

You can delete from PyPI and start over too.

**Comment by ocefpaf** [comment]
> You can delete from PyPI and start over too.

Delete yes. Use the same name, no.

> It's no problem to do this and keep things in perfect sync.

Keeping them In sync is only one of the advantages of releasing a `post` or a new `micro` version. Anyways.. Sorry for the noise @etgalloway.

**Comment by bryevdv** [comment]
> Delete yes. Use the same name, no.

I see this is a fairly recent change from 2015. I had done it before then. 

In that case just bump to `0.3.1`. Speaking now as user, release versions like `0.3.0p1` are strange and  out of the ordinary. Don't give users surprises.

**Comment by etgalloway** [comment]
@ocefpaf , @bryevdv thanks for the quick response.

@ocefpaf -- this is an interesting discussion -- no need to apologize.

Personally,  I am fine with doing  `0.3` and `0.3.1` releases.  I was thinking of doing a `0.3.1` release to fix a number of minor issues (warning messages, etc.).  With `0.3` I just wanted to get something out the door.

@ocefpaf thanks for the reference to mpld3-feedstock.  I did not know that mpld3 was now available on conda -- it's been a while since I checked.

**Comment by ocefpaf** [comment]
> Personally, I am fine with doing 0.3 and 0.3.1 releases.

I prefer `micro` bumps better than `post` releases too.

> @ocefpaf thanks for the reference to mpld3-feedstock.

Let me know if you or anyone from @mpld3 wants to be a maintainer there.

**Comment by etgalloway** [comment]
@ocefpaf feel free to add me as a maintainer of mpld3-feedstock.

Thanks for putting mpld3 on conda-forge.

**Comment by etgalloway** [comment]
v0.3 has been released.

It is now available on [pypi](https://pypi.python.org/pypi/mpld3).  It is also [installable from conda-forge](https://github.com/conda-forge/mpld3-feedstock#installing-mpld3) thanks to the good work of @ocefpaf.

There are a few minor issues with the docs on github.io (which have not yet been updated).

**Comment by aflaxman** [comment]
Yay! Thank you @etgalloway !  This works for me with either of the following:
```
pip install mpld3
conda install --channel https://conda.anaconda.org/conda-forge mpld3
```

If I do `conda install mpld3`, I get version `0.2`. Does anyone know who we should tell about this?

**Comment by ocefpaf** [comment]
@aflaxman not sure. Maybe that URL is not OK and it is trying to get a cached version. I just tested:

```shell
> conda install -c conda-forge mpld3
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/filipe/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.3                 |                0       122.1 MB  defaults
    numpy-1.11.2               |           py35_0         6.1 MB  defaults
    cycler-0.10.0              |           py35_0          13 KB  conda-forge
    mpld3-0.3                  |           py35_0         1.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       129.2 MB
```

and you can see `mpld3 0.3` there...

**Comment by aflaxman** [comment]
sorry for being unclear. that works for me also.  who can we ask to update the main channel, so that `conda install mpld3` also gets version `0.3`?

**Comment by ocefpaf** [comment]
The whole reason we created conda-forge was to avoid doing that :smile:

But  we do try it sometimes, like https://github.com/conda-forge/shapely-feedstock/issues/5

Feel free to open a similar issue on `mpld3` or in https://github.com/ContinuumIO/anaconda-recipes

**Comment by smaret** [comment]
I'm a bit confused with the changes in that release. 

There is [milestone for v0.3](https://github.com/mpld3/mpld3/milestone/3) which is only 12% complete. For example, MathJax support (#14) is listed in the milestone, but it didn't make it to the release. This milestone should probably be updated. 

Also it would be good to have release notes on the [GitHub release page](https://github.com/mpld3/mpld3/releases) so that new users (such as myself) can easily figure out what are the changes in the new version.

**Comment by etgalloway** [comment]
Assuming no objections, I will go ahead and update the docs on github.io despite #407.

It would be good to fix #407 quickly, as part of the 0.3.1 release, at the latest.

**Comment by etgalloway** [comment]
It's time (actually past time) to close this issue.

@smaret Apologies for the lack of release notes, etc.  Ultimately, the v0.3 release was about getting something out the door, sooner rather than later, without much consideration to milestones, etc.

**Comment by soedr** [comment]
@etgalloway are you aware of any developments regarding the ability to rotate axis labels? Thanks in advance.
