### ISSUE TITLE
Applying PointLabelTooltip on multiple scatter collections

### ISSUE THREAD

**Issue by syaffers** [mpld3/mpld3#422]
Hi guys, I'm plotting multiple scatter points for a combined interactive legend and tooltip functionality on my plots. I realized that the `PointLabelTooltip` takes a single axes collections object but since I perform `ax.scatter` multiple times, I have multiple collections and have to iterate over the `ax.collections` and match the scatter groups separately. Is there a cleaner way to do this like combining the collections? If I iterate through the `ax.collections` is this going to create overhead in the javascript when I have lots of scatter groups? Please find my code below with some comments.

    X = np.random.random((30, 2)) * 10 - 5
    fig, ax = plt.subplots()

    ax.scatter(X[:15, 0], X[:15, 1], color="blue", label="Blue", alpha=0.3)
    ax.scatter(X[15:, 0], X[15:, 1], color="red", label="Red", alpha=0.3)
    labels = ["P%d" % i for i in range(30)]

    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.set_title("Real Title")

    box = ax.get_position()
    ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])

    handles, llabels = ax.get_legend_handles_labels() # return lines and labels
    interactive_legend = mpld3.plugins.InteractiveLegendPlugin(
        zip(handles, ax.collections), ['Blue', 'Red'], alpha_unsel=0.5, alpha_over=5,
        start_visible=True)

    #ideally this is a loop
    tooltip0 = mpld3.plugins.PointHTMLTooltip(ax.collections[0], labels=labels[:15])
    tooltip1 = mpld3.plugins.PointHTMLTooltip(ax.collections[1], labels=labels[15:])
    mpld3.plugins.connect(fig, tooltip0)
    mpld3.plugins.connect(fig, tooltip1)
    mpld3.plugins.connect(fig, interactive_legend)
    mpld3.show(fig)

**Comment by etgalloway** [comment]
Something like this should work:
```python
for collections, labels_chunk in zip(ax.collections, np.array_split(labels, 2)):
    tooltip = mpld3.plugins.PointHTMLTooltip(collections, labels=labels_chunk.tolist())
    mpld3.plugins.connect(fig, tooltip)

mpld3.plugins.connect(fig, interactive_legend)
```
