### ISSUE TITLE
How to change position of home icon?

### ISSUE THREAD

**Issue by skiniry** [mpld3/mpld3#425]
Hi, Just wondering if anyone can point me in the right direction as to what files I should be editing to change the position of the plugin icons in the bottom left corner of the plots?

**Comment by etgalloway** [comment]
These lines set the position of the toolbar: https://github.com/mpld3/mpld3/blob/3a7c29ad7e76186737cd91af22c5e7b7ed852ca3/src/toolbar/toolbar.js#L54-L55

**Comment by skiniry** [comment]
Perfect, thank you.
