### ISSUE TITLE
Using fig_to_html with MPL hist2d

### ISSUE THREAD

**Issue by bensongcorning** [mpld3/mpld3#453]
Note: mpld3 is no longer being actively maintained: feature requests & bug reports are likely to go unanswered. If you are interested in maintaining this project, please contact one of the repository owners.

Having an issue where the HTML version of my plot is looking blurry compared to the direct output from MPL figure. See below post for pics of both. Anyone run into a similar issue?

https://imgur.com/a/8EyVdyx

**Comment by parhammmm** [comment]
This is an interpolation issue. `mpld3` is not correctly translating the interpolation properly from `matplotlib`

See here: https://matplotlib.org/gallery/images_contours_and_fields/interpolation_methods.html

A possible immediate fix could be setting the following CSS:

```css
#fig000 .mpld3-image {
    image-rendering: pixelated;
}
```
change `#fig000` to your figures id.

We wont be able to easily support all the interpolation types but I think it would be good enough to distinguish between the pixelated and not when the rendering is being done in the front end.

**Comment by vladh** [comment]
@bensongcorning Let me know if you still need help with this issue or if I should close it!
