### ISSUE TITLE
Releasing update on pypi?

### ISSUE THREAD

**Issue by bluenote10** [mpld3/mpld3#461]
Would it be possible to release on updated version of mpld3 on pypi? I'm aware that the project isn't actively maintained anymore, but there have been a few bugfixes after 0.3 and it would be nice to have them on PyPI.

**Comment by shadowboxingskills** [comment]
I needed the latest version as well, so I forked the source and released a new package separately on PyPI. You may use it to get MPLD3 v0.4.12 --> pip install mpld3-valuegrid
Hope it helps until next official release is out (last push was in 2016..)

**Comment by cliffckerr** [comment]
Hi @bluenote10 and @shadowboxingskills -- we apologize for the delay! We just got permission to push to pypi yesterday, and are just doing some final-final checks before publishing it. So if you can wait 1-2 more days (hopefully that's not too much after 4 years...), it should be updated very soon. cc @vladh

**Comment by vladh** [comment]
@bluenote10 @shadowboxingskills The latest version (0.5.0) is now on PyPI. Thank you so much for your patience! Could you let me know if the new version fixes things for you?

**Comment by bluenote10** [comment]
Thank you very much! As far as I'm concerned the issue can be closed.
