### ISSUE TITLE
Docs : example of save_html with local js urls

### ISSUE THREAD

**Issue by mocquin** [mpld3/mpld3#481]
This is about a proposition to add somewhere in the doc an example of how to use [`save_html`](https://mpld3.github.io/modules/API.html#mpld3.fig_to_html) with the `d3_url` and `mpld3_url` in order to export a html figure for offline use.

In my case, I am absolutely not familiar with javascript, and was a bit confused on how to save a figure to a stand alone html file, I did not know from where/which files to download locally.
I ended up [posting on SO](https://stackoverflow.com/questions/64894886/export-standalone-offline-html-plot-of-matplotlib-figures-using-mpld3), but later found the cause of my problem (which was the lack of "file://" prefix in the path, and the use of back-slashs instead of forward-slashes).

I think it would be usefull for the lambda-user like me trying to export html figure for offline use to have somewhere in the doc something like : 

> To use a local version of the java-script libraries, like for offline local html :
>  - download the mpld3 package which contains the javascript libraries in [https://github.com/mpld3/mpld3/tree/master/mpld3/js](https://github.com/mpld3/mpld3/tree/master/mpld3/js)
> - then reference the javascript files in the `save_html` export function : 
```python
# note the "file://" prefix and the forward slashes
with open("graph.html", "w") as fileobj:
    mpld3.save_html(plt.gcf(), fileobj,
                    d3_url="file://C:/.../mpld3-master/mpld3/js/d3.v5.min.js",
                    mpld3_url="file://C:/.../mpld3-master/mpld3/js/mpld3.v0.5.1.min.js",
                    )
```

Thanks a lot for this great package

**Comment by vladh** [comment]
Hi @mocquin,

I think this is already documented, but perhaps not clearly enough, in the `mpld3.fig_to_html()` API documentation.

https://mpld3.github.io/modules/API.html#mpld3.fig_to_html

However, thanks to a great PR by @Samrose-Ahmed, I can also now recommend using the new `include_libraries=False` argument for `fig_to_html()`. I think this would be easier, since you can then include the libraries yourself in your own HTML.
