### ISSUE TITLE
Drag with constraints

### ISSUE THREAD

**Issue by maxclac** [mpld3/mpld3#483]
Hello!

I was thinking that it would be nice to program a pendulum with mpld3, where one can drag the tip of the pendulum and release.
Now, I would like to focus on the dragging part, ignoring the physics part of the problem for the moment.
So, I have one point that I can drag around with the constraint that it must stay at the same distance of some other point. Is it in principle possible to have this in mpld3?

Thanks a lot!

**Comment by vladh** [comment]
Hi @maxclac 

mpld3 doesn't directly support this kind of thing, but you could add it via the [plugin system](http://mpld3.github.io/plugins.html) if you'd like.

However, I would just generally say mpld3 is not the right tool for this task. I would suggest simply working directly with d3, which would give you a lot more flexibility and make your task a lot easier.

Hope that helps!

**Comment by bryevdv** [comment]
>  I would suggest simply working directly with d3, which would give you a lot more flexibility and make your task a lot easier.

Unless you are specifically wed to d3, there are mature Python based packages that can do interactive web vis, namely [Bokeh](https://docs.bokeh.org/en/latest/) and [Plotly](https://plotly.com)

**Comment by cliffckerr** [comment]
Hi @maxclac , @vladh 's right that this should be possible using mpld3 plugins, but you'd probably have to write a lot of custom Python and JavaScript code to get it working. @bryevdv is right that one of these other packages might have an out-of-the-box solution -- another option is [Altair](https://altair-viz.github.io/). There's a brief comparison of these libraries here: https://opensource.com/article/20/4/plot-data-python

**Comment by maxclac** [comment]
Thanks a lot for the useful comments!
