### ISSUE TITLE
InteractiveLegendPlugin - AttributeError: module 'collections' has no attribute 'Iterable'`

### ISSUE THREAD

**Issue by vaclavvesely** [mpld3/mpld3#508]
Hello 

I have encountered problem when using  InteractiveLegendPlugin [example](https://mpld3.github.io/examples/interactive_legend.html) with Python 3.10.2. 
I manged to solve the issue by changing mpld3\plugins.py", line 704
            `if isinstance(entry, collections.Iterable): `
to 
            `if isinstance(entry, collections.abc.Iterable):`

the error message: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module> 
  File "...\mpld3\plugins.py", line 675, in __init__
    mpld3_element_ids = self._determine_mpld3ids(plot_elements)
  File "...\mpld3\plugins.py", line 704, in _determine_mpld3ids
    if isinstance(entry, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by vladh** [comment]
Thanks! Fixed in [d2b8012](https://github.com/mpld3/mpld3/commit/d2b8012a6a704d9fac35d1a839ecf012514e4031), will be released in 0.5.8.
