### ISSUE TITLE
import mpld3 - DeprecationWarning

### ISSUE THREAD

**Issue by vaclavvesely** [mpld3/mpld3#509]
Hello I have encountered this deprecation warning when importing  mpld3

import mpld3
...\mpld3\mplexporter\renderers\base.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools 
or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion

**Comment by Bozydarek** [comment]
Here is a PR with a fix for this issue: https://github.com/mpld3/mplexporter/pull/64

**Comment by vladh** [comment]
Thank you, fixed and out in 0.5.9.
