### ISSUE TITLE
Callbacks to Python

### ISSUE THREAD

**Issue by frankNiessen** [mpld3/mpld3#528]
Hi, 

is there any officially supported way of getting a callback from a mpld3 plot to Python? 
Say I plot a cloud of points from python with mpld3 and I want to send the mask of an interactively selected subset back to python? 

Best wishes
Frank

**Comment by vladh** [comment]
Hi @frankNiessen!

There's no support for something like that right now, and I think it's out of scope for mpld3, but it could be done using the plugin system. For example, you could create a websocket server using Python, then send messages to it using a custom mpld3 plugin.

Hope that helps!
